### ISSUE TITLE
Cannot load coverage file

### ISSUE THREAD

**Issue by sinapis** [ryanluker/vscode-coverage-gutters#161]
Using VS code 1.26 and coverage gutters 2.1.1

Coverage file is not loaded automatically, even though it resides in root and names Icov.info. When I execute preview coverage report - no files are shown.

![image](https://user-images.githubusercontent.com/15230040/44061578-a82ac86a-9f61-11e8-881c-4e4b53a34dcc.png)

Not sure if that's important but I'm using C# and generating the icov file using coverlet.

**Comment by mulligan121** [comment]
I'm also running into this issue. I use istanbul & nyc so my icov file is in a `coverage` directory. I've also tried moving it into the root directory and still get the same error.

**Comment by ryanluker** [comment]
@sinapis Thanks for submitting an issue. I havent looked lately into the preview report functionality so I will have to take a look at that for the next bugfix release (2.1.2). In the meantime can you install [0] and see if version 2.0.x allows you to still use the preview functionality? 

[0] https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by nverinaud** [comment]
Same here ! How can I help to resolve this ?

**Comment by sinapis** [comment]
for me neither 1.3.0 or 2.0.1 worked.
any suggestions to make this work would be very welcome...

**Comment by mulligan121** [comment]
I found that 2.2.0 works fine on Mac, I couldn't get it to pick up the lcov file on Windows. I'm assuming it has something to do with the path to the lcov file.

**Comment by sinapis** [comment]
I'm on windows so we get a consistent behavior

**Comment by ryanluker** [comment]
Thanks for the extra info everyone. @nverinaud @sinapis and @mulligan121 and you try a few things for me and paste the resulting logs here?
1) checkout this repo and open the examples folder in vscode
2) turn on the coverage watch
3) open a source file or two from each of the language folders

You should all get something similar to this:
```
[1537324127343][coverageservice]: INITIALIZING
[1537324133723][coverageservice]: LOADING
[1537324133773][coverageservice]: Loading 5 file(s)
[1537324133857][lcovparser][convertPartialPathsToAbsolute]: Error: Found too many files with partial path __init__.py
[1537324133996][coverageservice]: Caching 13 coverage(s)
[1537324133997][coverageservice]: READY
[1537324139781][coverageservice]: RENDERING
[1537324139783][renderer][section file path]: c:\dev\vscode-coverage-gutters\example\python\python\foobar\tests\foo\a.py
[1537324139784][coverageservice]: READY
[1537324145722][coverageservice]: RENDERING
[1537324145723][coverageservice]: READY
[1537324145785][coverageservice]: RENDERING
[1537324145786][renderer][section file path]: /home/ryan/dev/vscode-coverage-gutters/example/php/src/testCoverage/testMain2/main2.php
[1537324145791][coverageservice]: READY
[1537324155317][coverageservice]: RENDERING
[1537324155317][coverageservice]: READY
[1537324155353][coverageservice]: RENDERING
[1537324155354][renderer][section file path]: c:\dev\vscode-coverage-gutters\example\java\my-app\src\main\java\com\mycompany\app\App.java
[1537324155359][coverageservice]: READY
[1537324158623][coverageservice]: RENDERING
[1537324158624][coverageservice]: READY
[1537324159037][coverageservice]: RENDERING
[1537324159037][renderer][section file path]: /mnt/c/dev/vscode-coverage-gutters/example/node/test-coverage.js
[1537324159051][coverageservice]: READY
```
Hopefully we can get this worked out!

**Comment by mcauto** [comment]
Same here... on Mac version 1.3.1

**Comment by ryanluker** [comment]
@mcauto version 1.3.1 is quite old can you try the latest version (2.2.0)?

**Comment by mcauto** [comment]
@ryanluker 
I installed it from vscode marketplace.

Before download
![image](https://user-images.githubusercontent.com/15080806/46567664-808cd200-c971-11e8-828a-7dddff37c35c.png)

After download
<img width="271" alt="after download" src="https://user-images.githubusercontent.com/15080806/46567671-94d0cf00-c971-11e8-97cb-34d16653adfa.png">

**Comment by mulligan121** [comment]
I finally found some free time to debug the issue I was having on my Windows machine. If you have symlinks in any directory when coverage gutters looks for the lcov file it will throw an EPERM error.

```
glob error Error: EPERM: operation not permitted, scandir `<DIRECTORY>`
```

This is a really common issue when file crawling on Windows and I've ran into it with multiple node modules in the past. If I have time in the next few days I'll see if I can find a fix for this.

**Comment by ryanluker** [comment]
@mcauto I think microsoft keeps old builds of my extension and then gives you the one that best matches your vscode version (2.2.0 requires 1.27.x and up for example). Do you have the latest vscode version?

**Comment by mcauto** [comment]
@ryanluker
My vscode version is 1.19.2
so I updated vscode 1.27.x version. 
but occur same error.. `could not find a Coverage file.`

**Comment by ryanluker** [comment]
@mcauto depending on the positioning of the coverage file (needs to be in the folder / workspace you have open) it will cause you to get this error. Can you look at the example project(s) and see if you can get the coverage to be picked up by using their folder structure? https://github.com/ryanluker/vscode-coverage-gutters/tree/master/example

**Comment by mcauto** [comment]
@ryanluker 
I want to use coverage-gutters on [this project](https://github.com/woobia/woobia-note)
positioning of coverage file is this project root path.
What should I do? help me..

**Comment by ryanluker** [comment]
@mcauto the next release (2.2.1) will have some improvements to the relative path detection and the conversion to absolute paths, once that is out let me know if the issue still exists.
@mulligan121 I am thinking a way to fix this would be to allow a manual coverage file(s) `settings.json` attribute that people could set instead of the automatic one. I created a new feature ticket here for that #178

**Comment by tomchavakis** [comment]
Doesn't work at Windows, but works perfectly at Linux-Kubuntu 18.04.
The error is the same, can't load the lcov file.
I guess that it's something with the absolute paths of the lcov file.

Language: C# .Net Core
OS: Windows 10 x64
VSCode : Latest
Testing Framework: coverlet - https://github.com/tonerdo/coverlet
Coverage Gutters: 2.2.1

**Comment by mulligan121** [comment]
@ryanluker turns out it was an issue with the generated symlinks with the framework I was using. Windows classifies symlinks as either files, directories, or junctions (unlike unix based systems). The symlinks were being treated as files when they were actually directories, causing the issue with glob. We switched over to junctions instead and coverage gutters works fine on Windows for me now.

**Comment by tomchavakis** [comment]
@ryanluker all the example projects worked. I use coverlet and dotnet core for this project. I can produce a sample of lcov.info in case that helps.

**Comment by ryanluker** [comment]
@tomchavakis yes a sample lcov.info would assist in the debugging thanks.

**Comment by tomchavakis** [comment]
navigate to the test folder and generate the coverage file
dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./lcov.info Example.csproj

After running again the command it is possible to view the coverage-gutters.

**Comment by rvanmaanen** [comment]
@tomchavakis that will create a single lcov.info for each test project and coverage gutters won't merge it's coverage results (I think it shows the results of the last file it finds) so that needs to be done beforehand with coverlet.

The way this is done is by supplying these arguments: `"dotnet-test-explorer.testArguments": "--filter Category!=Integration /p:CollectCoverage=true \"/p:CoverletOutputFormat=\\\"json,lcov\\\"\" /p:CoverletOutput=..\\lcov /p:MergeWith=..\\lcov.json"` (yes including all the escaping and extra quotes)

This will create a lcov.json and lcov.info in the root of the workspace and it'll merge the coverage.json each run and then generate a lcov.info based on that merged file. So the endresult is 1 big lcov.info file with coverage from all test projects.

There is still an issue here, because it'll merge with any existing lcov.json file, also one from a previous run. So there's still some work to do at the coverlet plugin. Other issues are that it'll not update the merged file properly when removing tests (it seems only to add coverage and not remove lines that aren't covered anymore) and it'll crash if there isn't a file to merge with (which is troublesome with the first project you'll run tests on).

For now I did 2 things:
- Write the merged coverage files not to the root, but to 1 single project directory (although there are more), this fixes the problem with coveragegutters not picking up the file.

`"dotnet-test-explorer.testArguments": "--filter Category!=Integration /p:CollectCoverage=true \"/p:CoverletOutputFormat=\\\"json,lcov\\\"\" /p:CoverletOutput=..\\Project\\lcov /p:MergeWith=..\\Project\\lcov.json",`

- Altered the csproj of one of the **testproject** (not the actual implementation, that gets build more than once) to include this:

  <Target Name="ResetCoverageFile" AfterTargets="Build">
    <Copy SourceFiles="..\Project\lcov.empty" DestinationFiles="..\Project\lcov.json" />
  </Target>

lcov.empty is an empty json file, so that will result in a clean slate each time coveragegutters runs, builds all projects and executes all tests. Coverage won't be updated when executing single tests.

Sorry for a long and maybe difficult to follow answer, but thought I'd share what resulted in a workable solution for me.

**Comment by tomchavakis** [comment]
@rvanmaanen thank you very much for the detailed answer. It is very useful to merge the lcov from different projects and the explanation was great !!!

**Comment by Shelim** [comment]
I can't produce lcov file, my project is C++ and I use [OpenCppCoverage](https://github.com/OpenCppCoverage/OpenCppCoverage) which is able to produce cov.xml only...

**Comment by ryanluker** [comment]
@tomchavakis were you able to get the coverage to show after using @rvanmaanen 's detailed example? @Shelim the extension will look for a few default coverage file names and should be able to pick up cov.xml, you can change the names it looks for by setting a different array string here https://github.com/ryanluker/vscode-coverage-gutters/blob/master/package.json#L127.

**Comment by Shelim** [comment]
@ryanluker I've already tried that... It would be better if I could specify the path inside project to the directory containing cov.xml ; If this matter, I have multi-root workspace in VS Code

**Comment by tomchavakis** [comment]
@ryanluker the @rvanmaanen answer was really helpful. When I ran again the coverlet command in order to generate the lcov file I get the coverage display from VS Code. So the issue has been resolved from my end.

**Comment by ryanluker** [comment]
@Shelim that makes sense I have a ticket open to track that feature https://github.com/ryanluker/vscode-coverage-gutters/issues/178 already so I will close this ticket in the meantime as most of the other issues have been solved in here.
