### ISSUE TITLE
parse remote coverge files

### ISSUE THREAD

**Issue by mohamedahmed01** [ryanluker/vscode-coverage-gutters#249]
I always develop on a vm "Homestead" using ssh , 
it would be great if VS code can read the coverage from the vm,
Either using remote ssh something like local/remote file mapping .

**Comment by ryanluker** [comment]
@mohamedahmed01 thanks for submitting an issue! I would have to investigate vscode's remote project capabilities but at minimum choosing a network file could be something that is supported as it would be no different then loading the file locally. 

There might be some extra functionality around authentication if it was over ssh but otherwise there is already functionality. Another option is the feature that lets you choose a "remote" path for the coverage to swap paths out for (see the example project that uses a remote nodejs project for an example of this).

**Comment by ryanluker** [comment]
@mohamedahmed01 this might actually be achieved better with the newish remote connection extensions microsoft developed https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack . Going to close this for now instead but let me know if this helps any!
