### ISSUE TITLE
Coverage blocks breakpoints

### ISSUE THREAD

**Issue by junalmeida** [ryanluker/vscode-coverage-gutters#382]
**Describe the bug**
When coverage gutter is shown, breakpoints can't be enabled or disabled.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable a coverage gutter
2. Try to set or remove a breakpoint when gutter appears

**Expected behaviour**
I've seen a GitHub extension that also shows UI widgets on the gutter area that does not block the use of breakpoints, so I expect something like that. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Extension Version [e.g. 2.0.0] 2.10.2
 - VSCode Version [e.g. 1.21.0] 1.72.2

**Additional context**

**Comment by ryanluker** [comment]
@junalmeida Thanks for the issue! This is a known current issue afaik but it might have been fixed by microsoft 🤔.
https://github.com/ryanluker/vscode-coverage-gutters/issues?q=is%3Aissue+is%3Aclosed+breakpoint

In the meantime, you can follow the tips n tricks section here on how to use a workaround.
https://github.com/ryanluker/vscode-coverage-gutters#tips-and-tricks

**Comment by ryanluker** [comment]
Closing due to this being a known issue.
