### ISSUE TITLE
[Documentation] Example Java Gradle Project

### ISSUE THREAD

**Issue by EagleoutIce** [ryanluker/vscode-coverage-gutters#440]
**Is your feature request related to a problem? Please describe.**
I had difficulties in finding a starting point for using the extension with gradle.

**Describe the solution you'd like**
A new Java Example for gradle would be nice.

**Describe alternatives you've considered**
I think, extending #369 would be fine as well!

**Additional context**
If desired, I can create the example project / extend the quickstart documentation.

**Comment by ryanluker** [comment]
@EagleoutIce Thanks for the ticket!
We always welcome contributions and improvements, so no worries there.

I have also merged the quickstart readme you pinged me on so that can be extended as well (maybe include a link from the main readme still).

We have example projects [here](https://github.com/ryanluker/vscode-coverage-gutters/tree/master/example/java) using maven but you probably already found those, thus your want for gradle examples.
