### ISSUE TITLE
where do i put lcov file?

### ISSUE THREAD

**Issue by sinh927** [ryanluker/vscode-coverage-gutters#77]
I ran angular test with coverage.
The file has been created.
However, this plugin does not work.
why?

**Comment by ryanluker** [comment]
hello sinh, do you have a custom named lcov file by chance? you can define a partial path / file name by using the ```coverage-gutters.lcovname``` setting. Can you also try and check out this project and run the example project tests and see if you can see the coverage then? To assist in the debugging could you also give the partial file path to the file you mentioned?

**Comment by pintocarlos** [comment]
I'm also running into the same issue.
I am using nyc https://www.npmjs.com/package/nyc lcov reporter option
`nyc --reporter=lcov` which generates the following file structure:

<img width="232" alt="screen shot 2017-07-15 at 1 07 18 am" src="https://user-images.githubusercontent.com/1060904/28236678-055e4a9c-68fa-11e7-95e6-8f1c8f80bf01.png">

Is this what the extension is expecting or is it something different?
I'd love to try this extension, please advise. Thanks!

**Comment by pintocarlos** [comment]
I tested your example project and it works correctly. Im going to assume that you depend on the coverage.json file and not on the lconv.info, which I believe is the more common one.

Any plans on supporting the text file instead of the json file only?

**Comment by ryanluker** [comment]
hey @pintocarlos thanks for bringing more information to this issue. currently the extension only supports the lcov.info files (as you mentioned they are the more common) but this file can be anywhere inside the root of your project (see https://github.com/ryanluker/vscode-coverage-gutters/blob/2e8565fa1515ae29806bc673892709b3f6ce99b0/src/lcov.ts#L27 for the blob find of the file). The lcov name setting you mentioned allows you to specify another name for the blob search to look for, within the root path of the project. ie: ```"coverage-gutters.lcovname": "yourcustomlcovnamehere.info"``` I also couldnt get nyc to produce coverage for my example project either... I do use nyc to produce coverage in other projects though and the extension works on those. Let me know if you get an further.

**Comment by pintocarlos** [comment]
Hi @ryanluker I figured out what the problem was.
The extensions Watcher will not start parsing the code coverage in the lcov file unless you are currently in a file that actually has tests and is covered by the lcov file.

Take for instance the following scenario:
- package.json file is the only file open in the project
- Coverage Gutters is Enabled.
- Project is reloaded to enable extension.
- Project reloads with package.json open, which does not have any tests of course and is not included in the lcov file being generated by nyc.
- A message appears that there is no code coverage found.
- Switch to any other file that actually has coverage requires to manually click on the button to parse coverage.
- Now the watcher is active for files that do have coverage and are opened afterwards.

In essence, I think what would be great is if you check if no watcher is running, then try to enable it for the last opened file if it has coverage in the lconv file.

I hope this helps.
Thanks,
Carlos

**Comment by ryanluker** [comment]
@pintocarlos thanks for the extra info! In the 1.1 release (coming soon) the watch will always start now, [see code here if interested](https://github.com/ryanluker/vscode-coverage-gutters/pull/79/commits/017ee8b039dc02e2ad1a9af8e76801485dedd803), which should facilitate the flow you mentioned! I will leave this ticket open until friday-ish before closing it (if you or sinh has further issues you can always open another ticket 😄 )

**Comment by ryanluker** [comment]
> > Hi @ryanluker I figured out what the problem was. First of all it was not related to the location of the file. I ended up leaving the settings option empty and letting it use the default path: `coverage/lconv.info`.
> > The issue is that the extensions "Watcher" will not start parsing the code coverage in the lcov file unless you are currently in a file that actually has tests and is covered by the lcov file.
> 
> Wow, you're the best! I was picking some top rated tool and ended up with the same combo, and this comment really made it work!

Excellent, glad to see comments from +7 years ago proving useful!
