### ISSUE TITLE
Intra-line code coverage indications

### ISSUE THREAD

**Issue by jayongg** [ryanluker/vscode-coverage-gutters#90]
Hi,

when I have a ternary operation and tests that only execute one code path, I would like an indication that only certain lines/columns were executed. Instead I see that the whole line is green.

Similarly if I have an if statement and an else.  Possible to have an option to show squiggly lines instead of gutters?

(low priority :) )

**Comment by ryanluker** [comment]
Hey @jayongg thanks for the issue 😄 . currently you can do line coverage instead of gutter coverage through the settings (see my post here for info https://github.com/ryanluker/vscode-coverage-gutters/issues/87#issuecomment-316275141). Could this be related to your other typescript issue? I as able to have partial (orange) indicators for javascript ternaries. 
![save2](https://user-images.githubusercontent.com/1335972/29054937-429b5dc0-7bae-11e7-9138-3b238d49effe.PNG)

**Comment by jayongg** [comment]
Hey hey!  No not related to typescript issue. You are able to see coverage of .ts files?

As for ternary operators out of curiosity are you able to see which particular conditions were covered?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ryanluker** [comment]
ahh I see what you mean now about the coverage. no the coverage does not show for the specific condition that is "uncovered" it simply shows you that something on that line is not. Currently I can not think of a clean way (other then the green squiggles you mentioned)... in other extensions I have seen other people use symbols to try to better show the extent of the coverage but I do not think that would match what the extension currently offers. One option I could investigate would be to draw two colors on a line to try to show the difference in coverage but that would be quite the project 😃 .

**Comment by jayongg** [comment]
Hmm is it possible to have vscode highlight part of a line (as opposed to swuiggles)?  Actually I think the real question is - is it possible to read intra line info from a lcov file? I presume it is :)

**Comment by ryanluker** [comment]
Closing this one as it has gotten quite stale, could potentially work on this again after the caching enhancements #106
